# gsh-ecom-monorepo -> gosmarthome.in
server {
    listen 80;
    server_name gosmarthome.in www.gosmarthome.in;

    location / {
        proxy_pass http://127.0.0.1:9200;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# portfolio-monorepo -> shafeeq.dev
server {
    listen 80;
    server_name shafeeq.dev www.shafeeq.dev;

    location / {
        proxy_pass http://127.0.0.1:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# sai -> sai.shafeeq.dev
server {
    listen 80;
    server_name sai.shafeeq.dev;
    
    # Needs higher upload limit for Audio transcription API
    client_max_body_size 50M;

    location / {
        proxy_pass http://127.0.0.1:9100;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Websocket support for real-time features
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

# my-pro-gravity-axiom -> axiom.shafeeq.dev
server {
    listen 80;
    server_name axiom.shafeeq.dev;

    # Serve static files from this directory
    root /var/www/axiom.shafeeq.dev;
    
    # Primary index file
    index index.axiom.html;

    location / {
        try_files $uri $uri/ /index.axiom.html;
    }
}
